baseURL = "https://holyshrimp.xyz/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Dmitry Popov"
copyright = ":face_holding_back_tears:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Dmitry Popov"
  headline = "DevOps Engineer"
  image = "img/memoji.png"
  links = [
    { cv = { href = "/cv/CV_Popov_DevOps.pdf", text = "cv eng"} },
    { email = { href = "mailto:me@holyshrimp.xyz", text = " " } },
    { linkedin = { href = "https://linkedin.com/in/dmipopov", text = " "} },
    { telegram = { href = "https://t.me/holyshrimp", text = " "} },
#    { github = { href = "https://github.com/holyshrimp", text = " " } },
#    { gitlab = { href = "https://gitlab.com/holyshrimp", text = " "} },
  ]

[params]
  attribution = false